# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: 'LiVeAction'
author: 'Dan Jacobellis'
copyright: '2024'
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", README.md, "examples/*"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"


# Information about where the book exists on the web
repository:
  url: https://ut-sysml.github.io/liveaction  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

sphinx:
  config:
      html_theme_options:
          repository_provider: github
      html_show_copyright: false   